#!/usr/bin/env python3

import argparse
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("math")
    args = parser.parse_args()
    print(eval(str(args.math)))

if __name__ == "__main__":
    main()
